imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        dbname:   "%database_name%"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    handlers:
      main:
          type: rotating_file
          max_files: 20
          path:   "%kernel.logs_dir%/%kernel.environment%.log"
          level:  error